package br.com.Interface;

import java.sql.*;
import br.com.Conexao.ConexaoBD;
import br.com.Conexao.LoginBD;
import java.awt.Image;
import java.io.FileInputStream;
import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author aluno
 */
public class CadastroView extends javax.swing.JFrame {
    
    LoginBD lbd = new LoginBD();
    ConexaoBD cbd = new ConexaoBD();
    private Connection con;
    private PreparedStatement pst;
    
    private FileInputStream fis;
    
    private int tamanho;
    
    public CadastroView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtEmail = new javax.swing.JTextField();
        jtNome = new javax.swing.JTextField();
        jpSenha = new javax.swing.JPasswordField();
        jNasc = new javax.swing.JFormattedTextField();
        jbCadastrar = new javax.swing.JButton();
        jbAddFoto = new javax.swing.JButton();
        jlFotoPerfil = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtEmail.setBackground(new java.awt.Color(230, 225, 225));
        jtEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtEmail.setForeground(new java.awt.Color(0, 0, 0));
        jtEmail.setBorder(null);
        getContentPane().add(jtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 330, 50));

        jtNome.setBackground(new java.awt.Color(230, 225, 225));
        jtNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtNome.setForeground(new java.awt.Color(0, 0, 0));
        jtNome.setBorder(null);
        getContentPane().add(jtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 460, 330, 50));

        jpSenha.setBackground(new java.awt.Color(230, 225, 225));
        jpSenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jpSenha.setForeground(new java.awt.Color(0, 0, 0));
        jpSenha.setBorder(null);
        getContentPane().add(jpSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 590, 330, 50));

        jNasc.setBackground(new java.awt.Color(230, 225, 225));
        jNasc.setBorder(null);
        jNasc.setForeground(new java.awt.Color(0, 0, 0));
        jNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        jNasc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(jNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 590, 330, 50));

        jbCadastrar.setContentAreaFilled(false);
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jbCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 690, 440, 50));

        jbAddFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/1486564407-plus-green_81521.png"))); // NOI18N
        jbAddFoto.setContentAreaFilled(false);
        jbAddFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbAddFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddFotoActionPerformed(evt);
            }
        });
        getContentPane().add(jbAddFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, 50, 50));

        jlFotoPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/4043232-avatar-batman-comics-hero_113278.png"))); // NOI18N
        getContentPane().add(jlFotoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbAddFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddFotoActionPerformed
        upFoto();
    }//GEN-LAST:event_jbAddFotoActionPerformed

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        cadastrar();
    }//GEN-LAST:event_jbCadastrarActionPerformed
    
    public JPasswordField getJpSenha() {
        return jpSenha;
    }
    
    public void setJpSenha(JPasswordField jpSenha) {
        this.jpSenha = jpSenha;
    }
    
    public JTextField getJtEmail() {
        return jtEmail;
    }
    
    public void setJtEmail(JTextField jtEmail) {
        this.jtEmail = jtEmail;
    }
    
    public JTextField getJtNome() {
        return jtNome;
    }
    
    public void setJtNome(JTextField jtNome) {
        this.jtNome = jtNome;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroView().setVisible(true);
            }
        });
    }

    private void upFoto() {
        JFileChooser jfc = new JFileChooser();
        jfc.setDialogTitle("Selecionar foto de perfil");
        jfc.setFileFilter(new FileNameExtensionFilter("Arquivo de imagens (*.PNG,*.JPG,*.JPEG)", "png", "jpg", "jpeg"));
        int resultado = jfc.showOpenDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            try {
                fis = new FileInputStream(jfc.getSelectedFile());
                tamanho = (int) jfc.getSelectedFile().length();
                Image foto = ImageIO.read(jfc.getSelectedFile()).getScaledInstance(jlFotoPerfil.getWidth(), jlFotoPerfil.getHeight(), Image.SCALE_SMOOTH);
                jlFotoPerfil.setIcon(new ImageIcon(foto));
                jlFotoPerfil.updateUI();
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }

    private void cadastrar() {
        String inserir = "insert into login (nome,email,foto,senha,data_nasc) values(?,?,?,?,?)";
        try {
            
            pst = con.prepareStatement(inserir);
            pst.setString(1, jtNome.getText());
            pst.setString(2, jtEmail.getText());
            pst.setString(3, jNasc.getText());
            pst.setString(4, jpSenha.getText());
            pst.setBlob(5, fis, tamanho);
        } catch (Exception e) {
            System.out.println("Erro no cadastro" + e);
        }
    }

    private void status() {
        try {
            con = cbd.conectar();
            if (con == null) {
                System.out.println("Erro de conexão");
            } else {
                System.out.println("Conectado ao banco de dados");
            }
            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JFormattedTextField jNasc;
    private javax.swing.JButton jbAddFoto;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JLabel jlFotoPerfil;
    private javax.swing.JPasswordField jpSenha;
    private javax.swing.JTextField jtEmail;
    private javax.swing.JTextField jtNome;
    // End of variables declaration//GEN-END:variables
}
