package br.com.Interface;

import br.com.Controlador.ControladorLogin;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author aluno
 */
public class LoginView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtEmail = new javax.swing.JTextField();
        jpSenha = new javax.swing.JPasswordField();
        jbEntrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtEmail.setBackground(new java.awt.Color(230, 225, 225));
        jtEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtEmail.setForeground(new java.awt.Color(0, 0, 0));
        jtEmail.setBorder(null);
        getContentPane().add(jtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 360, 50));

        jpSenha.setBackground(new java.awt.Color(230, 225, 225));
        jpSenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jpSenha.setForeground(new java.awt.Color(0, 0, 0));
        jpSenha.setBorder(null);
        getContentPane().add(jpSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, 360, 50));

        jbEntrar.setBorder(null);
        jbEntrar.setContentAreaFilled(false);
        jbEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(jbEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 613, 470, 60));

        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 730, 150, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEntrarActionPerformed
        
        if (jtEmail.getText().matches("") || jpSenha.getText().matches("")) {
            JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos!");
        }else{
        
            ControladorLogin login = new ControladorLogin();
            try {
            login.loginUsuario(this);
            
        } catch (SQLException sql) {
                System.out.println("Erro");           
// Logger.getLogger(LoginView.class.getName()).log(Level.SEVERE, null, sql);
        }                   
    }
    }//GEN-LAST:event_jbEntrarActionPerformed
    
    public void fechar(){
        System.exit(0);
    }
    
    public JPasswordField getJpSenha() {
        return jpSenha;
    }

    public void setJpSenha(JPasswordField jpSenha) {
        this.jpSenha = jpSenha;
    }

    public JTextField getJtEmail() {
        return jtEmail;
    }

    public void setJtEmail(JTextField jtEmail) {
        this.jtEmail = jtEmail;
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbEntrar;
    private javax.swing.JPasswordField jpSenha;
    private javax.swing.JTextField jtEmail;
    // End of variables declaration//GEN-END:variables
}
